### ISSUE TITLE
MP3 Tags -> umlaute ermöglichen

### ISSUE THREAD

**Issue by stemaa14** [stemaa14/MusicBox#10]
Bei Titel/Interpret/Album werden keine Umlaute im Titel auf der Seite angezeigt. Auf unicode umwandeln?

**Comment by stemaa14** [comment]
WICHITG! Umlaute geben Fehler!

**Comment by stemaa14** [comment]
```
Traceback (most recent call last):
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\site-packages\waitress-1.0.1-py2.7.egg\waitress\channel.py", line 338, in service
    task.service()
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\site-packages\waitress-1.0.1-py2.7.egg\waitress\task.py", line 169, in service
    self.execute()
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\site-packages\waitress-1.0.1-py2.7.egg\waitress\task.py", line 399, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\site-packages\pyramid\router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\site-packages\pyramid\router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\site-packages\pyramid\tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\site-packages\pyramid\tweens.py", line 22, in excview_tween
    response = handler(request)
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\site-packages\pyramid\router.py", line 127, in handle_request
    root = root_factory(request)
  File "c:\users\stema\documents\schule\3ahif\syp1\newvenv\musicbox\musicbox\models.py", line 105, in appmaker
    build_playlist(files)
  File "c:\users\stema\documents\schule\3ahif\syp1\newvenv\musicbox\musicbox\models.py", line 55, in build_playlist
    tags['title'] = title.encode('utf8')
  File "C:\Users\stema\Documents\Schule\3AHIF\SYP1\newVenv\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 25: invalid start byte
```
